import Footer from "@/components/sections/footer"
import Header from "@/components/sections/header"
import type { Metadata } from "next"
import { mont } from "./fonts"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="text-[15px] 2xl:text-[16px]">
      <body className={`${mont.className}`}>
        <div className="space-y-8">

        <Header />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  )
}
